// Copyright 2026 akshat-git-jpg and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newReportingSearchGetCmd(flags *rootFlags) *cobra.Command {
	var flagTransactionId string
	var flagTransactionType string
	var flagTransactionStatus string
	var flagTransactionAmount string
	var flagTransactionCurrency string
	var flagStartDate string
	var flagEndDate string
	var flagPaymentInstrumentType string
	var flagStoreId string
	var flagTerminalId string
	var flagFields string
	var flagBalanceAffectingRecordsOnly string
	var flagPageSize int
	var flagPage string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "search-get",
		Short:       "Lists transactions. Specify one or more query parameters to filter the transaction that appear in the response.",
		Example:     "  paypal-txns-pp-cli reporting search-get --start-date 2026-01-15 --end-date 2026-01-15",
		Annotations: map[string]string{"pp:endpoint": "reporting.search-get", "pp:method": "GET", "pp:path": "/v1/reporting/transactions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("start-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "start-date")
			}
			if !cmd.Flags().Changed("end-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "end-date")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/reporting/transactions"
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "reporting", path, map[string]string{
				"transaction_id":                 fmt.Sprintf("%v", flagTransactionId),
				"transaction_type":               fmt.Sprintf("%v", flagTransactionType),
				"transaction_status":             fmt.Sprintf("%v", flagTransactionStatus),
				"transaction_amount":             fmt.Sprintf("%v", flagTransactionAmount),
				"transaction_currency":           fmt.Sprintf("%v", flagTransactionCurrency),
				"start_date":                     fmt.Sprintf("%v", flagStartDate),
				"end_date":                       fmt.Sprintf("%v", flagEndDate),
				"payment_instrument_type":        fmt.Sprintf("%v", flagPaymentInstrumentType),
				"store_id":                       fmt.Sprintf("%v", flagStoreId),
				"terminal_id":                    fmt.Sprintf("%v", flagTerminalId),
				"fields":                         fmt.Sprintf("%v", flagFields),
				"balance_affecting_records_only": fmt.Sprintf("%v", flagBalanceAffectingRecordsOnly),
				"page_size":                      fmt.Sprintf("%v", flagPageSize),
				"page":                           fmt.Sprintf("%v", flagPage),
			}, nil, flagAll, "page", "page", "page_size", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagTransactionId, "transaction-id", "", "Filters the transactions in the response by a PayPal transaction ID.")
	cmd.Flags().StringVar(&flagTransactionType, "transaction-type", "", "Filters the transactions in the response by a PayPal transaction event code.")
	cmd.Flags().StringVar(&flagTransactionStatus, "transaction-status", "", "Filters the transactions in the response by a PayPal transaction status code.")
	cmd.Flags().StringVar(&flagTransactionAmount, "transaction-amount", "", "Filters the transactions in the response by a gross transaction amount range.")
	cmd.Flags().StringVar(&flagTransactionCurrency, "transaction-currency", "", "Filters the transactions in the response by a [three-character ISO-4217 currency")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Filters the transactions in the response by a start date and time, in [Internet date and time format](https://tools.")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Filters the transactions in the response by an end date and time, in [Internet date and time format](https://tools.ietf.")
	cmd.Flags().StringVar(&flagPaymentInstrumentType, "payment-instrument-type", "", "Filters the transactions in the response by a payment instrument type. Value is either: CREDITCARD .")
	cmd.Flags().StringVar(&flagStoreId, "store-id", "", "Filters the transactions in the response by a store ID.")
	cmd.Flags().StringVar(&flagTerminalId, "terminal-id", "", "Filters the transactions in the response by a terminal ID.")
	cmd.Flags().StringVar(&flagFields, "fields", "transaction_info", "Indicates which fields appear in the response. Value is a single field or a comma-separated list of fields.")
	cmd.Flags().StringVar(&flagBalanceAffectingRecordsOnly, "balance-affecting-records-only", "Y", "Indicates whether the response includes only balance-impacting transactions or all transactions. Value is either: Y .")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "The number of items to return in the response.")
	cmd.Flags().StringVar(&flagPage, "page", "1", "The zero-relative start index of the entire list of items that are returned in the response.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
