// Copyright 2026 akshat-git-jpg and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newReportingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "reporting",
		Short:       "Use the Transaction Search API to get the history of transactions for a PayPal account.",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newReportingBalancesGetCmd(flags))
	cmd.AddCommand(newReportingSearchGetCmd(flags))
	return cmd
}
