-- Backfill the canonical slug for every card that predates 0003_card_slug.sql.
-- Generated by running apps/tutorial-tracker-app/src/shared/slug.ts (slugify +
-- mintSlug) over the 76 live cards in card-id order. Card-id order is also
-- chronological order here, so a -2/-3 suffix reads as "the 2nd/3rd time this
-- video was made" - see the plan for the evidence.
--
-- Idempotent: every UPDATE is guarded on slug IS NULL, so re-running this
-- migration can never renumber a slug that has already been minted.

-- r0027  Wise vs Revolut (My HONEST Recommendation)
UPDATE cards SET slug = 'wise-vs-revolut-my-honest-recommendation' WHERE id = 'r0027' AND slug IS NULL;
-- r0028  BEST Email Marketing Software 2024: Which One Should You Choose?
UPDATE cards SET slug = 'best-email-marketing-software-2024-which' WHERE id = 'r0028' AND slug IS NULL;
-- r0029  Wise vs PayPal (My HONEST Recommendation)
UPDATE cards SET slug = 'wise-vs-paypal-my-honest-recommendation' WHERE id = 'r0029' AND slug IS NULL;
-- r0030  ActiveCampaign vs Mailchimp : Which one is right for you?
UPDATE cards SET slug = 'activecampaign-vs-mailchimp-which-one' WHERE id = 'r0030' AND slug IS NULL;
-- r0031  ActiveCampaign vs MailerLite : Which one is right for you?
UPDATE cards SET slug = 'activecampaign-vs-mailerlite-which-one' WHERE id = 'r0031' AND slug IS NULL;
-- r0032  Pictory Coupon Code (Highest Pictory Discount Code) – Still Working
UPDATE cards SET slug = 'pictory-coupon-code-highest-pictory' WHERE id = 'r0032' AND slug IS NULL;
-- r0033  Fliki AI Coupon Code (Highest Fliki AI Discount Code) – Still Working
UPDATE cards SET slug = 'fliki-ai-coupon-code-highest-fliki-ai' WHERE id = 'r0033' AND slug IS NULL;
-- r0034  Invideo Coupon Code (Highest Invideo Discount code) – Still Working
UPDATE cards SET slug = 'invideo-coupon-code-highest-invideo' WHERE id = 'r0034' AND slug IS NULL;
-- r0035  Heygen Ai Review : Best AI Avatar Generator
UPDATE cards SET slug = 'heygen-ai-review-best-ai-avatar' WHERE id = 'r0035' AND slug IS NULL;
-- r0036  Heygen vs Synthesia: Which one is right for you?
UPDATE cards SET slug = 'heygen-vs-synthesia-which-one-right' WHERE id = 'r0036' AND slug IS NULL;
-- r0037  VidIQ Vs TubeBuddy: Which one is right for you?
UPDATE cards SET slug = 'vidiq-vs-tubebuddy-which-one-right' WHERE id = 'r0037' AND slug IS NULL;
-- r0038  Shopify VS WooCommerce: Which one is right for you?
UPDATE cards SET slug = 'shopify-vs-woocommerce-which-one-right' WHERE id = 'r0038' AND slug IS NULL;
-- r0039  Pictory vs Invideo vs Fliki vs Synthesia vs Lumen5 | Best AI Video Generator
UPDATE cards SET slug = 'pictory-vs-invideo-vs-fliki-vs-synthesia' WHERE id = 'r0039' AND slug IS NULL;
-- r0040  Fliki AI Coupon Code – Still Working
UPDATE cards SET slug = 'fliki-ai-coupon-code-still-working' WHERE id = 'r0040' AND slug IS NULL;
-- r0041  Envato Elements Coupon Code – Still Working
UPDATE cards SET slug = 'envato-elements-coupon-code-still' WHERE id = 'r0041' AND slug IS NULL;
-- r0042  Invideo AI Coupon Code – Still Working
UPDATE cards SET slug = 'invideo-ai-coupon-code-still-working' WHERE id = 'r0042' AND slug IS NULL;
-- r0043  Submagic Promo Code – Still Working
UPDATE cards SET slug = 'submagic-promo-code-still-working' WHERE id = 'r0043' AND slug IS NULL;
-- r0044  TubeBuddy Coupon Code – Still Working
UPDATE cards SET slug = 'tubebuddy-coupon-code-still-working' WHERE id = 'r0044' AND slug IS NULL;
-- r0045  VidIQ Promo Code | VidIQ Coupon Code – Still Working
UPDATE cards SET slug = 'vidiq-promo-code-vidiq-coupon-code-still' WHERE id = 'r0045' AND slug IS NULL;
-- r0046  Namecheap Coupon Code – Still Working
UPDATE cards SET slug = 'namecheap-coupon-code-still-working' WHERE id = 'r0046' AND slug IS NULL;
-- r0047  TradingView Coupon Code | TradingView Discount Code – Still Working
UPDATE cards SET slug = 'tradingview-coupon-code-tradingview' WHERE id = 'r0047' AND slug IS NULL;
-- r0048  Dropship.io Promo Code – Still Working
UPDATE cards SET slug = 'dropship-io-promo-code-still-working' WHERE id = 'r0048' AND slug IS NULL;
-- r0049  AutoDS Coupon Code – Still Working
UPDATE cards SET slug = 'autods-coupon-code-still-working' WHERE id = 'r0049' AND slug IS NULL;
-- r0050  Leonardo Ai Coupon Code | Leonardo Ai Discount Code – Still Working
UPDATE cards SET slug = 'leonardo-ai-coupon-code-leonardo-ai' WHERE id = 'r0050' AND slug IS NULL;
-- r0051  Invideo AI Coupon Code – Still Working
UPDATE cards SET slug = 'invideo-ai-coupon-code-still-working-2' WHERE id = 'r0051' AND slug IS NULL;
-- r0052  Jenni AI Promo Code – Still Working
UPDATE cards SET slug = 'jenni-ai-promo-code-still-working' WHERE id = 'r0052' AND slug IS NULL;
-- r0053  PiPiADS Coupon Code – Still Working
UPDATE cards SET slug = 'pipiads-coupon-code-still-working' WHERE id = 'r0053' AND slug IS NULL;
-- r0054  Systeme.io Coupon Code – Still Working
UPDATE cards SET slug = 'systeme-io-coupon-code-still-working' WHERE id = 'r0054' AND slug IS NULL;
-- r0055  Synthesia Promo Code – Still Working
UPDATE cards SET slug = 'synthesia-promo-code-still-working' WHERE id = 'r0055' AND slug IS NULL;
-- r0056  Murf AI Promo Code – Still Working
UPDATE cards SET slug = 'murf-ai-promo-code-still-working' WHERE id = 'r0056' AND slug IS NULL;
-- r0057  EverBee Promo Code – Still Working
UPDATE cards SET slug = 'everbee-promo-code-still-working' WHERE id = 'r0057' AND slug IS NULL;
-- r0058  Jungle Scout Coupon Code – Still Working
UPDATE cards SET slug = 'jungle-scout-coupon-code-still-working' WHERE id = 'r0058' AND slug IS NULL;
-- r0059  Glitching Ai Promo Code – Still Working
UPDATE cards SET slug = 'glitching-ai-promo-code-still-working' WHERE id = 'r0059' AND slug IS NULL;
-- r0060  InVideo Studio vs InVideo AI: Which one is right for you?
UPDATE cards SET slug = 'invideo-studio-vs-invideo-ai-which-one' WHERE id = 'r0060' AND slug IS NULL;
-- r0061  Fliki Ai Promo code  – Still Working
UPDATE cards SET slug = 'fliki-ai-promo-code-still-working' WHERE id = 'r0061' AND slug IS NULL;
-- r0062  Fliki AI Coupon Code – Still Working
UPDATE cards SET slug = 'fliki-ai-coupon-code-still-working-2' WHERE id = 'r0062' AND slug IS NULL;
-- r0063  Invideo AI Discount Code– Still Working
UPDATE cards SET slug = 'invideo-ai-discount-code-still-working' WHERE id = 'r0063' AND slug IS NULL;
-- r0064  Invideo AI Coupon Code – Still Working
UPDATE cards SET slug = 'invideo-ai-coupon-code-still-working-3' WHERE id = 'r0064' AND slug IS NULL;
-- r0065  Everbee Coupon Code – Still Working
UPDATE cards SET slug = 'everbee-coupon-code-still-working' WHERE id = 'r0065' AND slug IS NULL;
-- r0066  EverBee Promo Code – Still Working
UPDATE cards SET slug = 'everbee-promo-code-still-working-2' WHERE id = 'r0066' AND slug IS NULL;
-- r0067  TradingView Coupon Code | TradingView Discount Code – Still Working
UPDATE cards SET slug = 'tradingview-coupon-code-tradingview-2' WHERE id = 'r0067' AND slug IS NULL;
-- r0068  TradingView  Promo Code– Still Working
UPDATE cards SET slug = 'tradingview-promo-code-still-working' WHERE id = 'r0068' AND slug IS NULL;
-- r0069  Submagic Coupon Code – Still Working
UPDATE cards SET slug = 'submagic-coupon-code-still-working' WHERE id = 'r0069' AND slug IS NULL;
-- r0070  Submagic Promo Code – Still Working
UPDATE cards SET slug = 'submagic-promo-code-still-working-2' WHERE id = 'r0070' AND slug IS NULL;
-- r0071  Elevenlabs Promo Code | Elevenlabs Coupon Code – Still Working – Still Working
UPDATE cards SET slug = 'elevenlabs-promo-code-elevenlabs-coupon' WHERE id = 'r0071' AND slug IS NULL;
-- r0072  Crayo AI Promo Code – Still Working
UPDATE cards SET slug = 'crayo-ai-promo-code-still-working' WHERE id = 'r0072' AND slug IS NULL;
-- r0073  Creatify AI Coupon Code – Still Working
UPDATE cards SET slug = 'creatify-ai-coupon-code-still-working' WHERE id = 'r0073' AND slug IS NULL;
-- r0074  Filmora Coupon Code 2025 | Wondershare coupon code | Filmora 14 Coupon Code – Still Working
UPDATE cards SET slug = 'filmora-coupon-code-2025-wondershare' WHERE id = 'r0074' AND slug IS NULL;
-- r0075  Jenni AI Promo Code – Still Working
UPDATE cards SET slug = 'jenni-ai-promo-code-still-working-2' WHERE id = 'r0075' AND slug IS NULL;
-- r0076  Helium 10 Coupon Code – Still Working
UPDATE cards SET slug = 'helium-10-coupon-code-still-working' WHERE id = 'r0076' AND slug IS NULL;
-- r0077  HeyGen Coupon Code | Heygen Promo Code – Still Working
UPDATE cards SET slug = 'heygen-coupon-code-heygen-promo-code' WHERE id = 'r0077' AND slug IS NULL;
-- r0078  Kittl Coupon code – Still Working
UPDATE cards SET slug = 'kittl-coupon-code-still-working' WHERE id = 'r0078' AND slug IS NULL;
-- r0079  Lovable AI Promo Code – Still Working
UPDATE cards SET slug = 'lovable-ai-promo-code-still-working' WHERE id = 'r0079' AND slug IS NULL;
-- r0080  HeyGen vs Synthesia: BEST AI Avatar Video Generator
UPDATE cards SET slug = 'heygen-vs-synthesia-best-ai-avatar-video' WHERE id = 'r0080' AND slug IS NULL;
-- r0081  Heygen vs Synthesia vs Creatify vs D-ID vs Veed.io | Best AI Avatar Generator
UPDATE cards SET slug = 'heygen-vs-synthesia-vs-creatify-vs-d-id' WHERE id = 'r0081' AND slug IS NULL;
-- r0082  HeyGen AI Review & Tutorial
UPDATE cards SET slug = 'heygen-ai-review-tutorial' WHERE id = 'r0082' AND slug IS NULL;
-- r0083  Base44 vs Lovable: Which is the best AI builder?
UPDATE cards SET slug = 'base44-vs-lovable-which-best-ai-builder' WHERE id = 'r0083' AND slug IS NULL;
-- r0084  N8N vs Flowise: Which Is The Best No-Code Automation Tool?
UPDATE cards SET slug = 'n8n-vs-flowise-which-best-no-code' WHERE id = 'r0084' AND slug IS NULL;
-- r0085  LangChain vs N8N:  Which One is Better for Automations?
UPDATE cards SET slug = 'langchain-vs-n8n-which-one-better' WHERE id = 'r0085' AND slug IS NULL;
-- r0086  OpenArt Promo Code – Working
UPDATE cards SET slug = 'openart-promo-code-working' WHERE id = 'r0086' AND slug IS NULL;
-- r0087  Base44 Coupon Code
UPDATE cards SET slug = 'base44-coupon-code' WHERE id = 'r0087' AND slug IS NULL;
-- r0088  N8N coupon code
UPDATE cards SET slug = 'n8n-coupon-code' WHERE id = 'r0088' AND slug IS NULL;
-- r0089  Lovable Vs Base44 Vs Bolt Vs Replit Vs Cursor
UPDATE cards SET slug = 'lovable-vs-base44-vs-bolt-vs-replit-vs' WHERE id = 'r0089' AND slug IS NULL;
-- r0090  Submagic Coupon Code
UPDATE cards SET slug = 'submagic-coupon-code' WHERE id = 'r0090' AND slug IS NULL;
-- r0091  Book Bolt Coupon Code
UPDATE cards SET slug = 'book-bolt-coupon-code' WHERE id = 'r0091' AND slug IS NULL;
-- r0105  How to Make a Realistic AI Clone of Yourself
UPDATE cards SET slug = 'how-make-realistic-ai-clone-yourself' WHERE id = 'r0105' AND slug IS NULL;
-- r0107  N8n vs  flowise vs zapier vs make vs langchain | Best No-Code Automation Tool
UPDATE cards SET slug = 'n8n-vs-flowise-vs-zapier-vs-make-vs' WHERE id = 'r0107' AND slug IS NULL;
-- r0108  Submagic vs Opus Clip
UPDATE cards SET slug = 'submagic-vs-opus-clip' WHERE id = 'r0108' AND slug IS NULL;
-- r0109  lovable vs claude code
UPDATE cards SET slug = 'lovable-vs-claude-code' WHERE id = 'r0109' AND slug IS NULL;
-- r0110  How To Create Long AI Animation Videos with Consistent Characters |how to create animated story videos with ai ( full guide)
UPDATE cards SET slug = 'how-create-long-ai-animation-videos-with' WHERE id = 'r0110' AND slug IS NULL;
-- r0111  How to Create a Consistent AI Influencer that Gets Sponsors (Full Course)
UPDATE cards SET slug = 'how-create-consistent-ai-influencer-gets' WHERE id = 'r0111' AND slug IS NULL;
-- r0112  egypt - how to create realistic ai talking avatar (with 100% Lip Sync)
UPDATE cards SET slug = 'egypt-how-create-realistic-ai-talking' WHERE id = 'r0112' AND slug IS NULL;
-- r0113  higgsfiled vs openart vs synthesa vs heygen vs arcads |best ai video generator
UPDATE cards SET slug = 'higgsfiled-vs-openart-vs-synthesa-vs' WHERE id = 'r0113' AND slug IS NULL;
-- r0114  best realistic ai avatar generator for youtube videos
UPDATE cards SET slug = 'best-realistic-ai-avatar-generator' WHERE id = 'r0114' AND slug IS NULL;
-- r0115  OpenArt AI Review
UPDATE cards SET slug = 'openart-ai-review' WHERE id = 'r0115' AND slug IS NULL;
-- r0116  openart VS higgsfield
UPDATE cards SET slug = 'openart-vs-higgsfield' WHERE id = 'r0116' AND slug IS NULL;
