#!/usr/bin/env node
// Reads a plan.json and renders every scene as its own MP4 (plus a stitched preview reel).
// Usage:  node scripts/render-plan.mjs plans/<slug>/plan.json [--scene title,pricing]
//
// Outputs to: cutaways/<slug>/
//   01-title.mp4 ... 07-cta.mp4
//   00-preview-all.mp4 (stitched, for fast scrubbing)
//   shot-notes.md
//
// Why one MP4 per scene: editor drops the ones they want onto their NLE timeline
// without re-encoding. Preview reel exists only for the editor to scrub through
// quickly before picking.

import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..");

const args = process.argv.slice(2);
const planPath = args[0];
if (!planPath || planPath.startsWith("--")) {
  console.error("Usage: node scripts/render-plan.mjs plans/<slug>/plan.json [--only=title,pricing] [--no-preview]");
  process.exit(1);
}

const onlyArg = args.find((a) => a.startsWith("--only="));
const onlyTypes = onlyArg ? onlyArg.split("=")[1].split(",").map((s) => s.trim()) : null;
const noPreview = args.includes("--no-preview");

const absPlanPath = path.resolve(process.cwd(), planPath);
const plan = JSON.parse(readFileSync(absPlanPath, "utf-8"));
if (!plan.slug || !Array.isArray(plan.scenes)) {
  throw new Error(`plan.json is missing slug or scenes[]: ${absPlanPath}`);
}

const slug = plan.slug;
const outDir = path.join(PROJECT_ROOT, "cutaways", slug);
mkdirSync(outDir, { recursive: true });

const TYPE_TO_COMP = {
  title: "Title",
  toc: "Toc",
  section: "Section",
  comparison: "Comparison",
  pricing: "Pricing",
  verdict: "Verdict",
  cta: "Cta",
};

// Filter scenes if --only=
const targets = plan.scenes
  .map((scene, i) => ({ scene, index: i }))
  .filter(({ scene }) => (onlyTypes ? onlyTypes.includes(scene.type) : true));

if (targets.length === 0) {
  console.error("No scenes matched the --only filter.");
  process.exit(1);
}

const remotionEntry = path.join(PROJECT_ROOT, "src", "index.ts");
const tempPropsFiles = [];

function runRender(compId, propsFilePath, outFile) {
  // Spawn `npx remotion render` from the project root with all the right flags.
  const cmd = [
    "npx",
    "--no-install",
    "remotion",
    "render",
    JSON.stringify(remotionEntry),
    compId,
    JSON.stringify(outFile),
    `--props=${JSON.stringify(propsFilePath)}`,
    "--codec=h264",
    "--pixel-format=yuv420p",
    "--color-space=bt709",
    "--log=info",
    "--quiet",
  ].join(" ");
  execSync(cmd, { stdio: "inherit", cwd: PROJECT_ROOT });
}

// Render every selected scene to its own MP4.
for (const { scene, index } of targets) {
  const n = String(index + 1).padStart(2, "0");
  const name = `${n}-${scene.type}`;
  const outFile = path.join(outDir, `${name}.mp4`);
  const propsFile = path.join(outDir, `.props-${name}.json`);
  writeFileSync(propsFile, JSON.stringify(scene.data, null, 2));
  tempPropsFiles.push(propsFile);
  console.log(`→ Rendering ${name}.mp4 ...`);
  runRender(TYPE_TO_COMP[scene.type], propsFile, outFile);
}

// Render the stitched preview reel.
if (!noPreview && !onlyTypes) {
  const previewProps = path.join(outDir, ".props-preview.json");
  writeFileSync(previewProps, JSON.stringify({ plan }, null, 2));
  tempPropsFiles.push(previewProps);
  const previewOut = path.join(outDir, "00-preview-all.mp4");
  console.log("→ Rendering 00-preview-all.mp4 (stitched reel) ...");
  runRender("Preview", previewProps, previewOut);
}

// Clean up temp props files.
for (const f of tempPropsFiles) {
  try { rmSync(f); } catch { /* ignore */ }
}

// Write a starter shot-notes.md the editor can refer to.
const sceneLines = plan.scenes.map((scene, i) => {
  const n = String(i + 1).padStart(2, "0");
  const filename = `${n}-${scene.type}.mp4`;
  const summary = (() => {
    switch (scene.type) {
      case "title": return scene.data.title;
      case "toc": return `${scene.data.items.length} items`;
      case "section": return `Section ${scene.data.number} — ${scene.data.title}`;
      case "comparison": return `${scene.data.tools.join(" vs ")}`;
      case "pricing": return scene.data.items.map((i) => `${i.label} $${i.value}`).join(" · ");
      case "verdict": return `Winner: ${scene.data.winner}`;
      case "cta": return `Code: ${scene.data.code}`;
      default: return "";
    }
  })();
  return `- **${filename}** — ${summary}`;
}).join("\n");

const shotNotes = `# Shot notes — ${plan.title}

Generated by render-plan.mjs. These cutaways are ready to drop onto your NLE timeline.

Drop order is your call — \`shot-notes.md\` is a starting suggestion based on the order in plan.json, not a binding script.

## Cutaways

${sceneLines}

## Suggested placement (rough)

| Cutaway | Suggested moment in the video |
|---|---|
| 01-title | Very start (0:00). Voiceover hook overlays on top. |
| 02-toc | After the hook lands, before the first content section. |
| 03-section | Use one section divider per major part of the video. |
| 04-comparison | Anywhere comparison appears in the script (often the summary). |
| 05-pricing | When numbers come up — usually mid-section, hold ~5s. |
| 06-verdict | Right after you state your pick. Holds 5s by default. |
| 07-cta | Near the end, just before the outro. Pair with discount mention. |

Editor can re-time, trim, or skip any cutaway. All clips are lossless H.264 at 1920×1080 / 30fps.
`;
writeFileSync(path.join(outDir, "shot-notes.md"), shotNotes);

console.log(`\n✓ Done. Output in: ${outDir}`);
