// @vitest-environment jsdom
import { describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen } from "@testing-library/react";
import { LinkHealth } from "../src/client/LinkHealth";
const program = { slug: "openart", name: "OpenArt", kind: "affiliate", target_url: "https://openart.ai/?via=me", network: "other", approval_status: "approved", coupon_status: "unknown", coupon_code: "", coupon_url: "", coupon_terms: "", dashboard_url: "", dashboard_credentials: "", notes: "", probe_enabled: 1, last_checked_at: null, last_status: null, last_final_url: null, previous_final_url: null, created_at: 0, updated_at: 0, updated_by: "" };
const stub = (body: unknown, status = 200) => vi.fn(async () => ({ ok: status < 400, status, json: async () => body }) as Response);
const renderHealth = () => render(<LinkHealth onFix={vi.fn()} />);
describe("LinkHealth", () => {
  it("names the 06:00 IST first run", async () => { global.fetch = stub({ latest: null, programs: [] }); renderHealth(); expect(await screen.findByText(/first runs at 06:00 IST/)).toBeTruthy(); });
  it("shows all-fine count and last run", async () => { global.fetch = stub({ latest: { ran_at: 1, checked: 4, unverifiable: 0, issues_json: "[]" }, programs: [] }); renderHealth(); expect(await screen.findByText(/All 4 links are fine/)).toBeTruthy(); expect(screen.getByText(/Last run/)).toBeTruthy(); });
  it("groups money and changed issues with their details", async () => { global.fetch = stub({ latest: { ran_at: 1, checked: 2, unverifiable: 2, issues_json: JSON.stringify([{ code: "no_credit_marker", slug: "openart", detail: "lost code" }, { code: "changed_destination", slug: "openart", detail: "Was old; now new." }]) }, programs: [program] }); renderHealth(); expect(await screen.findByText("Costing you money now")).toBeTruthy(); expect(screen.getByText("Changed since last week")).toBeTruthy(); expect(screen.getByText("lost code")).toBeTruthy(); expect(screen.getByText(/Was old; now new/)).toBeTruthy(); expect(screen.getByText(/2 links block robots/)).toBeTruthy(); expect(screen.getByRole("button", { name: "Open all" })).toBeTruthy(); });
  it("shows Admin forbidden state", async () => { global.fetch = stub({}, 403); renderHealth(); expect(await screen.findByText("You need the Admin role to see link health.")).toBeTruthy(); expect(screen.queryByRole("button", { name: "Re-check now" })).toBeNull(); });
  it("disables recheck when health fails", async () => { global.fetch = stub({}, 500); renderHealth(); const retry = await screen.findByRole("button", { name: "Retry" }); expect(retry.hasAttribute("disabled")).toBe(true); expect(retry.getAttribute("title")).toBe("Health could not load"); });
  it("opens the program form action for its slug", async () => { const fix = vi.fn(); global.fetch = stub({ latest: { ran_at: 1, checked: 1, unverifiable: 0, issues_json: JSON.stringify([{ code: "no_credit_marker", slug: "openart", detail: "lost" }]) }, programs: [program] }); render(<LinkHealth onFix={fix} />); fireEvent.click(await screen.findByRole("button", { name: "Fix programme" })); expect(fix).toHaveBeenCalledWith(expect.objectContaining({ slug: "openart" })); });
});
