// @vitest-environment jsdom
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { LinksTab } from "../src/client/LinksTab";
import { ProgramForm } from "../src/client/ProgramForm";

const PROGRAM = { slug: "openart", name: "OpenArt", kind: "affiliate", target_url: "https://openart.ai/home/?via=seema", network: "website", approval_status: "approved", coupon_status: "received", coupon_code: "AGROLLO", coupon_url: "", coupon_terms: "", dashboard_url: "", dashboard_credentials: "", notes: "", probe_enabled: 1, last_checked_at: null, last_status: null, last_final_url: null, previous_final_url: null, created_at: 0, updated_at: 0, updated_by: "" } as const;
const VOCAB = { kinds: ["affiliate", "external"], networks: ["website", "other"], approvalStatuses: ["approved", "unknown"], couponStatuses: ["received", "unknown"] };
function stubFetch(routes: Record<string, unknown>) { return vi.fn(async (url: string) => { const key = Object.keys(routes).sort((a, b) => b.length - a.length).find((k) => String(url).startsWith(k)); if (!key) return { ok: false, status: 404, json: async () => ({}) } as Response; const payload = routes[key] as { status?: number; body?: unknown }; const status = payload?.status ?? 200; return { ok: status < 400, status, json: async () => payload?.body ?? routes[key] } as Response; }); }
function tab() { return <LinksTab rows={[]} onSaved={vi.fn()} />; }
function form(kind: "affiliate" | "external" = "affiliate", initial = null) { return <ProgramForm initial={initial} kind={kind} onClose={vi.fn()} onSaved={vi.fn()} />; }
beforeEach(() => { vi.useFakeTimers({ shouldAdvanceTime: true }); });
afterEach(() => { vi.restoreAllMocks(); vi.useRealTimers(); });

describe("LinksTab — Programs", () => {
  it("1 renders a program row from the API", async () => { global.fetch = stubFetch({ "/api/programs": { programs: [PROGRAM], vocab: VOCAB } }); render(tab()); expect(await screen.findByText("OpenArt")).toBeTruthy(); expect(screen.getByText("via=seema")).toBeTruthy(); });
  it("2 shows the three sub-tabs and opens Programs by default", async () => { global.fetch = stubFetch({ "/api/programs": { programs: [], vocab: VOCAB } }); render(tab()); expect(await screen.findByText("No programs yet.")).toBeTruthy(); expect(screen.getByRole("tab", { name: /Tracking links/ })).toBeTruthy(); expect(screen.getByRole("tab", { name: "Health" })).toBeTruthy(); });
  it("3 shows the empty state with an Import button when there are no programs", async () => { global.fetch = stubFetch({ "/api/programs": { programs: [], vocab: VOCAB } }); render(tab()); expect(await screen.findByRole("button", { name: "Import from the old sheet" })).toBeTruthy(); });
  it("4 shows a Retry button when the API 5xx's", async () => { global.fetch = stubFetch({ "/api/programs": { status: 500, body: {} } }); render(tab()); expect(await screen.findByRole("button", { name: "Retry" })).toBeTruthy(); });
  it("5 shows the Admin-role message on 403 and hides Add", async () => { global.fetch = stubFetch({ "/api/programs": { status: 403, body: {} } }); render(tab()); expect(await screen.findByText("You need the Admin role to manage links.")).toBeTruthy(); expect(screen.getByRole("button", { name: "Add affiliate" }).hasAttribute("disabled")).toBe(true); });
  it("6 tints a no_credit row and labels the code as lost", async () => { global.fetch = stubFetch({ "/api/programs": { programs: [{ ...PROGRAM, target_url: "https://openart.ai", last_status: "no_credit" }], vocab: VOCAB } }); render(tab()); expect(await screen.findByText("none found")).toBeTruthy(); expect(screen.getByText("OpenArt").closest("tr")?.className).toContain("bg-destructive/5"); });
  it("7 labels an external row's code column not expected", async () => { global.fetch = stubFetch({ "/api/programs": { programs: [{ ...PROGRAM, kind: "external" }], vocab: VOCAB } }); render(tab()); expect(await screen.findByText("not expected")).toBeTruthy(); });
  it("8 switching to Tracking links renders the grouped links view", async () => { global.fetch = stubFetch({ "/api/programs": { programs: [PROGRAM], vocab: VOCAB }, "/api/links": { links: [] } }); render(tab()); await screen.findByText("OpenArt"); fireEvent.click(screen.getByRole("tab", { name: "Tracking links" })); expect(await screen.findByText("No tracking links yet. Use Add -> Tracking links for a video.")).toBeTruthy(); expect(screen.queryByText("OpenArt")).toBeNull(); });
  it("shows the health shell", async () => { global.fetch = stubFetch({ "/api/programs": { programs: [], vocab: VOCAB } }); render(tab()); fireEvent.click(screen.getByRole("tab", { name: "Health" })); expect(await screen.findByText("Link health checks arrive with the guard.")).toBeTruthy(); });
  it("renders the imported count after importing", async () => { global.fetch = stubFetch({ "/api/programs": { programs: [], vocab: VOCAB }, "/api/programs/import-from-sheet": { imported: { affiliate: 2, external: 1 } } }); render(tab()); fireEvent.click(await screen.findByRole("button", { name: "Import from the old sheet" })); expect(await screen.findByText("Imported 2 affiliate + 1 external.")).toBeTruthy(); });
});
describe("ProgramForm", () => {
  async function validate(body: unknown) { global.fetch = stubFetch({ "/api/programs/validate": body }); render(form()); const input = screen.getByLabelText("Destination URL"); fireEvent.change(input, { target: { value: "openart.ai" } }); fireEvent.blur(input); await vi.advanceTimersByTimeAsync(500); }
  it("9 disables Save and shows the reason when the URL is refused", async () => { await validate({ ok: false, value: "", error: "Not a usable web address", warnings: [] }); expect(await screen.findByText("Not a usable web address")).toBeTruthy(); expect(screen.getByRole("button", { name: "Save program" }).hasAttribute("disabled")).toBe(true); });
  it("10 shows the auto-added https:// as Saving as and keeps Save enabled", async () => { await validate({ ok: true, value: "https://openart.ai/home/?via=seema", error: null, warnings: [] }); expect(await screen.findByText("Saving as: https://openart.ai/home/?via=seema")).toBeTruthy(); expect(screen.getByRole("button", { name: "Save program" }).hasAttribute("disabled")).toBe(false); });
  it("11 keeps Save enabled for a warning, and renders the warning text", async () => { await validate({ ok: true, value: "https://bookbolt.io/", error: null, warnings: [{ code: "no_credit_marker", message: "No affiliate code found" }] }); expect(await screen.findByText("No affiliate code found")).toBeTruthy(); expect(screen.getByRole("button", { name: "Save program" }).hasAttribute("disabled")).toBe(false); });
  it("12 hides the coupon block for kind external", () => { global.fetch = stubFetch({}); render(form("external")); expect(screen.queryByLabelText("Coupon code")).toBeNull(); expect(screen.getByText(/No affiliate programme/)).toBeTruthy(); });
  it("13 makes slug read-only when editing", () => { global.fetch = stubFetch({}); render(form("affiliate", PROGRAM)); expect((screen.getByLabelText("Slug") as HTMLInputElement).readOnly).toBe(true); });
  it("derives a slug from the name while adding", () => { global.fetch = stubFetch({}); render(form()); fireEvent.change(screen.getByLabelText("Name"), { target: { value: "Open Art Pro" } }); expect((screen.getByLabelText("Slug") as HTMLInputElement).value).toBe("open-art-pro"); });
  it("explains the empty-link state", () => { global.fetch = stubFetch({}); render(form()); expect(screen.getByText("No link yet — this programme cannot be published.")).toBeTruthy(); });
  it("renders dashboard credentials as a plain textarea", () => { global.fetch = stubFetch({}); render(form()); expect((screen.getByLabelText("Dashboard credentials") as HTMLTextAreaElement).type).toBe("textarea"); });
});
