// Copyright 2026 akshat-git-jpg and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type address struct {
	City        string `json:"city"`
	CountryCode string `json:"country_code"`
	Line1       string `json:"line1"`
	Line2       string `json:"line2"`
	PostalCode  string `json:"postal_code"`
	State       string `json:"state"`
}

type auction_info struct {
	AuctionBuyerId     string `json:"auction_buyer_id"`
	AuctionClosingDate string `json:"auction_closing_date"`
	AuctionItemSite    string `json:"auction_item_site"`
	AuctionSite        string `json:"auction_site"`
}

type balance_detail struct {
	AvailableBalance json.RawMessage `json:"available_balance"`
	Currency         string          `json:"currency"`
	Primary          bool            `json:"primary"`
	TotalBalance     json.RawMessage `json:"total_balance"`
	WithheldBalance  json.RawMessage `json:"withheld_balance"`
}

type balances_response struct {
	AccountId       string          `json:"account_id"`
	AsOfTime        string          `json:"as_of_time"`
	Balances        json.RawMessage `json:"balances"`
	LastRefreshTime string          `json:"last_refresh_time"`
}

type cart_info struct {
	ItemDetails     json.RawMessage `json:"item_details"`
	PaypalInvoiceId string          `json:"paypal_invoice_id"`
	TaxInclusive    bool            `json:"tax_inclusive"`
}

type checkout_option struct {
	CheckoutOptionName  string `json:"checkout_option_name"`
	CheckoutOptionValue string `json:"checkout_option_value"`
}

type error_400 struct {
	DebugId string          `json:"debug_id"`
	Details json.RawMessage `json:"details"`
	Links   json.RawMessage `json:"links"`
	Message string          `json:"message"`
	Name    string          `json:"name"`
}

type error_401 struct {
	DebugId string          `json:"debug_id"`
	Details json.RawMessage `json:"details"`
	Links   json.RawMessage `json:"links"`
	Message string          `json:"message"`
	Name    string          `json:"name"`
}

type error_403 struct {
	DebugId string          `json:"debug_id"`
	Details json.RawMessage `json:"details"`
	Links   json.RawMessage `json:"links"`
	Message string          `json:"message"`
	Name    string          `json:"name"`
}

type error_404 struct {
	DebugId string          `json:"debug_id"`
	Details json.RawMessage `json:"details"`
	Links   json.RawMessage `json:"links"`
	Message string          `json:"message"`
	Name    string          `json:"name"`
}

type error_409 struct {
	DebugId string          `json:"debug_id"`
	Details json.RawMessage `json:"details"`
	Links   json.RawMessage `json:"links"`
	Message string          `json:"message"`
	Name    string          `json:"name"`
}

type error_415 struct {
	DebugId string          `json:"debug_id"`
	Details json.RawMessage `json:"details"`
	Links   json.RawMessage `json:"links"`
	Message string          `json:"message"`
	Name    string          `json:"name"`
}

type error_422 struct {
	DebugId string          `json:"debug_id"`
	Details json.RawMessage `json:"details"`
	Links   json.RawMessage `json:"links"`
	Message string          `json:"message"`
	Name    string          `json:"name"`
}

type error_500 struct {
	DebugId string          `json:"debug_id"`
	Links   json.RawMessage `json:"links"`
	Message string          `json:"message"`
	Name    string          `json:"name"`
}

type error_503 struct {
	DebugId string          `json:"debug_id"`
	Links   json.RawMessage `json:"links"`
	Message string          `json:"message"`
	Name    string          `json:"name"`
}

type error_details struct {
	Description string `json:"description"`
	Field       string `json:"field"`
	Issue       string `json:"issue"`
	Location    string `json:"location"`
	Value       string `json:"value"`
}

type error_link_description struct {
	Href   string `json:"href"`
	Method string `json:"method"`
	Rel    string `json:"rel"`
}

type incentive_detail struct {
	IncentiveAmount      json.RawMessage `json:"incentive_amount"`
	IncentiveCode        string          `json:"incentive_code"`
	IncentiveProgramCode string          `json:"incentive_program_code"`
	IncentiveType        string          `json:"incentive_type"`
}

type incentive_info struct {
	IncentiveDetails json.RawMessage `json:"incentive_details"`
}

type item_detail struct {
	AdjustmentAmount    json.RawMessage `json:"adjustment_amount"`
	BasicShippingAmount json.RawMessage `json:"basic_shipping_amount"`
	CheckoutOptions     json.RawMessage `json:"checkout_options"`
	DiscountAmount      json.RawMessage `json:"discount_amount"`
	ExtraShippingAmount json.RawMessage `json:"extra_shipping_amount"`
	GiftWrapAmount      json.RawMessage `json:"gift_wrap_amount"`
	HandlingAmount      json.RawMessage `json:"handling_amount"`
	InsuranceAmount     json.RawMessage `json:"insurance_amount"`
	InvoiceNumber       string          `json:"invoice_number"`
	ItemAmount          json.RawMessage `json:"item_amount"`
	ItemCode            string          `json:"item_code"`
	ItemDescription     string          `json:"item_description"`
	ItemName            string          `json:"item_name"`
	ItemOptions         string          `json:"item_options"`
	ItemQuantity        string          `json:"item_quantity"`
	ItemUnitPrice       json.RawMessage `json:"item_unit_price"`
	TaxAmounts          json.RawMessage `json:"tax_amounts"`
	TaxPercentage       string          `json:"tax_percentage"`
	TotalItemAmount     json.RawMessage `json:"total_item_amount"`
}

type item_detail_tax_amount struct {
	TaxAmount json.RawMessage `json:"tax_amount"`
}

type link_description struct {
	Href   string `json:"href"`
	Method string `json:"method"`
	Rel    string `json:"rel"`
}

type money struct {
	CurrencyCode string `json:"currency_code"`
	Value        string `json:"value"`
}

type name struct {
	AlternateFullName string `json:"alternate_full_name"`
	FullName          string `json:"full_name"`
	GivenName         string `json:"given_name"`
	MiddleName        string `json:"middle_name"`
	Prefix            string `json:"prefix"`
	Suffix            string `json:"suffix"`
	Surname           string `json:"surname"`
}

type payer_info struct {
	AccountId     string          `json:"account_id"`
	Address       json.RawMessage `json:"address"`
	AddressStatus string          `json:"address_status"`
	CountryCode   string          `json:"country_code"`
	EmailAddress  string          `json:"email_address"`
	PayerName     json.RawMessage `json:"payer_name"`
	PayerStatus   string          `json:"payer_status"`
	PhoneNumber   json.RawMessage `json:"phone_number"`
}

type phone struct {
	CountryCode     string `json:"country_code"`
	ExtensionNumber string `json:"extension_number"`
	NationalNumber  string `json:"national_number"`
}

type search_response struct {
	AccountNumber         string          `json:"account_number"`
	EndDate               string          `json:"end_date"`
	LastRefreshedDatetime string          `json:"last_refreshed_datetime"`
	Links                 json.RawMessage `json:"links"`
	Page                  int             `json:"page"`
	StartDate             string          `json:"start_date"`
	TotalItems            int             `json:"total_items"`
	TotalPages            int             `json:"total_pages"`
	TransactionDetails    json.RawMessage `json:"transaction_details"`
}

type shipping_info struct {
	Address                  json.RawMessage `json:"address"`
	Method                   string          `json:"method"`
	Name                     string          `json:"name"`
	SecondaryShippingAddress json.RawMessage `json:"secondary_shipping_address"`
}

type store_info struct {
	StoreId    string `json:"store_id"`
	TerminalId string `json:"terminal_id"`
}

type transaction_detail struct {
	AuctionInfo     json.RawMessage `json:"auction_info"`
	CartInfo        json.RawMessage `json:"cart_info"`
	IncentiveInfo   json.RawMessage `json:"incentive_info"`
	PayerInfo       json.RawMessage `json:"payer_info"`
	ShippingInfo    json.RawMessage `json:"shipping_info"`
	StoreInfo       json.RawMessage `json:"store_info"`
	TransactionInfo json.RawMessage `json:"transaction_info"`
}

type transaction_info struct {
	AnnualPercentageRate      string          `json:"annual_percentage_rate"`
	AvailableBalance          json.RawMessage `json:"available_balance"`
	BankReferenceId           string          `json:"bank_reference_id"`
	CreditPromotionalFee      json.RawMessage `json:"credit_promotional_fee"`
	CreditTerm                string          `json:"credit_term"`
	CreditTransactionalFee    json.RawMessage `json:"credit_transactional_fee"`
	CustomField               string          `json:"custom_field"`
	DiscountAmount            json.RawMessage `json:"discount_amount"`
	EndingBalance             json.RawMessage `json:"ending_balance"`
	FeeAmount                 json.RawMessage `json:"fee_amount"`
	InstrumentSubType         string          `json:"instrument_sub_type"`
	InstrumentType            string          `json:"instrument_type"`
	InsuranceAmount           json.RawMessage `json:"insurance_amount"`
	InvoiceId                 string          `json:"invoice_id"`
	OtherAmount               json.RawMessage `json:"other_amount"`
	PaymentMethodType         string          `json:"payment_method_type"`
	PaymentTrackingId         string          `json:"payment_tracking_id"`
	PaypalAccountId           string          `json:"paypal_account_id"`
	PaypalReferenceId         string          `json:"paypal_reference_id"`
	PaypalReferenceIdType     string          `json:"paypal_reference_id_type"`
	ProtectionEligibility     string          `json:"protection_eligibility"`
	SalesTaxAmount            json.RawMessage `json:"sales_tax_amount"`
	ShippingAmount            json.RawMessage `json:"shipping_amount"`
	ShippingDiscountAmount    json.RawMessage `json:"shipping_discount_amount"`
	ShippingTaxAmount         json.RawMessage `json:"shipping_tax_amount"`
	TipAmount                 json.RawMessage `json:"tip_amount"`
	TransactionAmount         json.RawMessage `json:"transaction_amount"`
	TransactionEventCode      string          `json:"transaction_event_code"`
	TransactionId             string          `json:"transaction_id"`
	TransactionInitiationDate string          `json:"transaction_initiation_date"`
	TransactionNote           string          `json:"transaction_note"`
	TransactionStatus         string          `json:"transaction_status"`
	TransactionSubject        string          `json:"transaction_subject"`
	TransactionUpdatedDate    string          `json:"transaction_updated_date"`
}
